### ISSUE TITLE
Create data resource throws an error

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/collectory#114]
![image](https://user-images.githubusercontent.com/1606595/162851989-32e15e4e-fe1d-4dbf-b018-4f1bb900ea89.png)

**Comment by adam-collins** [comment]
Incorrect server config should be fixed now. 

Please test again.

**Comment by patkyn** [comment]
This is working. Thanks @adam-collins.

**Comment by peggynewman** [comment]
This isn't working anymore
