### ISSUE TITLE
Create new provider code throws error

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/collectory#140]
In the spirit of the previous errors on creating data providers and data resources:
https://github.com/AtlasOfLivingAustralia/collectory/issues/114
https://github.com/AtlasOfLivingAustralia/collectory/issues/123

the same error is thrown when creating a provider code

<img width="792" alt="image" src="https://user-images.githubusercontent.com/1271932/181135441-1e0cdf51-d193-4412-aca7-6dd7b52d08af.png">

Probably worth checking if the same occurs creating a provider map.

**Comment by vjrj** [comment]
About provider mapping #135 and #136.
