### ISSUE TITLE
Collections not listed alphabetically

### ISSUE THREAD

**Issue by MontseGBIF** [AtlasOfLivingAustralia/collectory#145]
In the tab "List" collections are not listed alphabetically

![image](https://user-images.githubusercontent.com/99327523/183612298-339704f6-7132-4b35-8757-83aa0241dd75.png)

**Comment by vjrj** [comment]
Similar screenshot in `ala-collectory` `1.6.4`

![image](https://user-images.githubusercontent.com/180085/183614688-21131217-e87b-4246-a89a-9ae4a646265f.png)

**Comment by MontseGBIF** [comment]
Ok

**Comment by sughics** [comment]
Implemented in #147
