### ISSUE TITLE
Collectory public view is able to Edit

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/collectory#151]
Edit button is accessible from the collectory public page. Logged in using private email

![image](https://user-images.githubusercontent.com/1606595/185026204-ba227830-3a5f-4965-85ae-8f63d5059fe9.png)

Dave Watts first reported this issue.

**Comment by sughics** [comment]
@vjrj , here's the non-oidc fix for this issue: https://github.com/AtlasOfLivingAustralia/collectory/pull/154. This has been merged to develop. 
This will be replaced with OIDC specific changes once the feature/oidc is merged to develop.

**Comment by vjrj** [comment]
Thanks indeed @sughics

**Comment by sughics** [comment]
Functional testing and OIDC testing results added here: https://confluence.csiro.au/display/ALASD/Collectory+Test+Plan

**Comment by sughics** [comment]
@vjrj  Please add this commit https://github.com/AtlasOfLivingAustralia/collectory/pull/153/commits/7764f806e70fff356ff8685153898307ced8dbcf to the non-oidc fork(s) of collectory to fix the following issue:   
It appears will check the wrong attribute in the isAuth (checks uid when uuid is passed in) method resulting the edit button to now show for non-admin editors.
