### ISSUE TITLE
Collectory - Repatriate data gets a 500 error

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/collectory#166]
In collectory.

See https://collections-test.ala.org.au/manage/searchForRepatResources

DP for GBIF, dp42, only has 400K records, but I expect more like 4-5m. Want to rerun but getting 500 error 

![Image](https://user-images.githubusercontent.com/1271932/197114631-be091bd4-73d4-48a6-9d16-fef811cfd8e0.png)

**Comment by adam-collins** [comment]
Should it be 4-5m records with the country `Australia`, or all countries? I am getting about 1.4m for AU.

**Comment by adam-collins** [comment]
Added role ROLE_COLLECTION_EDITOR and it has fixed the issue?

**Comment by peggynewman** [comment]
No, I'm still getting the error now.

**Comment by adam-collins** [comment]
Problem identified as the browser populating the hidden username/password fields.

https://github.com/AtlasOfLivingAustralia/collectory/pull/169

**Comment by sat01a** [comment]
Will be released as part of 3.1.1
