### ISSUE TITLE
Updating text Description for a dataProvider results in a 500 error. 

### ISSUE THREAD

**Issue by sughics** [AtlasOfLivingAustralia/collectory#172]
Error discovered during new testing of new test cases added to collections test document. 

Update: Error was caused due to missing `uid` param required for a description update. 

![Screenshot 2022-12-13 at 12 39 19 pm](https://user-images.githubusercontent.com/105408469/207205015-8330bba1-00f6-4fe4-be73-a3c890491e5a.png)

**Comment by sat01a** [comment]
Fix deployed to test, will be released as part of 3.1.1 release.
