### ISSUE TITLE
"Contact curator" button shows all collection contacts regardless of status

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/collectory#187]
The "Contact curator" button on individual records shows the full list of contacts for a collection. The collectory includes a "Make public" option in a contact's settings which determines whether or not they appear in the right sidebar on a collection's information page, however this setting is not respected when deciding what contacts to show when a user clicks "Contact curator" - it should, because a collection may have contacts who can edit its information but do not need to be publicly listed.

Reported by @timhicks-ala

**Comment by adam-collins** [comment]
Please provide an example

**Comment by adam-collins** [comment]
https://biocache.ala.org.au/occurrences/35993288-e206-4a2e-b0f3-736be0bfc18d

**Comment by adam-collins** [comment]
pull request https://github.com/AtlasOfLivingAustralia/collectory/pull/193

**Comment by sughics** [comment]
Additional fix for this change here: https://github.com/AtlasOfLivingAustralia/collectory/pull/198

**Comment by sughics** [comment]
Released with 3.2.2
