### ISSUE TITLE
Collectory: Missing default values for DwC field (basisOfRecord)

### ISSUE THREAD

**Issue by cha801p** [AtlasOfLivingAustralia/collectory#204]
Description: The "MaterialSample" default value is missing in the "basisOfRecord" field for the given data resource.
Example: [dr21633](https://collections-test.ala.org.au/dataResource/show/dr21633)

**Comment by sadeghim** [comment]
It would be good to add the missing ones from current standard: https://dwc.tdwg.org/terms/#dwc:basisOfRecord

**Comment by adam-collins** [comment]
Also align `type`, https://dwc.tdwg.org/list/#dc_type

**Comment by adam-collins** [comment]
pull request https://github.com/AtlasOfLivingAustralia/collectory/pull/205
