### ISSUE TITLE
Collections-test: problem creating ProviderMaps then causing 500 errors in collectory

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/collectory#206]
Looks like there's been a glitch with ProviderMaps when trying to create one again. Similar to what happened once before I think.  No idea why it happens

Getting this error: https://collections-test.ala.org.au/collection/list

Error 500: More than one row with the given identifier was found: 46, for class: [au.org](http://au.org/).ala.collectory.ProviderMap; nested exception is org.hibernate.HibernateException: More than one row with the given identifier was found: 46, for class: [au.org](http://au.org/).ala.collectory.ProviderMap
Servlet: grailsDispatcherServlet
URI: /collection/list
Exception Message: More than one row with the given identifier was found: 46, for class: [au.org](http://au.org/).ala.collectory.ProviderMap; nested exception is org.hibernate.HibernateException: More than one row with the given identifier was found: 46, for class: [au.org](http://au.org/).ala.collectory.ProviderMap
Caused by: More than one row with the given identifier was found: 46, for class: [au.org](http://au.org/).ala.collectory.ProviderMap; nested exception is org.hibernate.HibernateException: More than one row with the given identifier was found: 46, for class: [au.org](http://au.org/).ala.collectory.ProviderMap
Class: HibernateGormStaticApi
At Line: [120]

> Update(Sushant): This issue occurs when creating  a Provider Map if the selected collection is already listed in another existing provider map . This creates a duplicate entry in the database which throws an error on data retrieval.

**Comment by sughics** [comment]
Released with 3.2.2
