### ISSUE TITLE
Collectory - Collections File upload clearing Connection Parameters

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/collectory#207]
The data team has recently identified a number of problems with the Collectory **File Upload** function when attempting to upload data to an existing dataresource.
 
On clicking on the **Upload a data file** button in the 
File Upload section, some existing data for Connection Parameters and Data Mobilisation settings are removed.  

Most urgently:

1. **Darwin core terms that uniquely identify a record** is cleared. If not reset precisely this will result in UUIDs being incorrect on ingestion. 
2. **Incremental Load** flag is reset to unchecked and even if re-checked does not save on file upload. This has caused issues when it is assumed that the flag has been set and can result in a full-load instead of a merge occurring. 

It has also been noted that within the Data Mobilisation section, various properties, including the JSON map of parameters, are being inadvertently cleared.

Can this please be investigated as soon as possible as the current functionality has led to data load errors that have been a challenge to revert. 

any help is appreciated.

**Comment by adam-collins** [comment]
This is fixed

**Comment by rosemaryjoconnor** [comment]
Thanks so much Adam. I've been running some tests this morning and it is looking great.
________________________________
