### ISSUE TITLE
Collectory - editing contact role page UI needs something

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/collectory#213]
![Image](https://user-images.githubusercontent.com/1271932/249658633-d3831433-c175-4152-9065-19ad4d0f1750.png)

Reported by @peggynewman

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/collectory/commit/c8b67a127dde87ae345b293def346b92c41bead4

**Comment by adam-collins** [comment]
This is on collections test for testing
