### ISSUE TITLE
API - Collections Metadata Add field to Connection Parameters

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/collectory#216]
Collectory Metadata API:  https://docs.ala.org.au/openapi/index.html?urls.primaryName=metadata

Could the Connection Parameter for **dataURL** be exposed for a dataResource entity. 

For example:
          'https://api.ala.org.au/metadata/ws/dataResource/dr15865'

returns:
   "connectionParameters": {
        "protocol": "DwCA",
        "automation": false,
        "strip": false,
        "incremental": false,
        "termsForUniqueKey": [
            "catalogNumber"
        ]
    },
This may require authentication.

**Comment by sat01a** [comment]
Logged by @rosemaryjoconnor

**Comment by adam-collins** [comment]
This is a gateway problem. The service works when accessed directly.

**Comment by adam-collins** [comment]
The gateway is fixed. Of course an apikey header is required for some connection parameters.
