### ISSUE TITLE
Expert distribution data resources are all set to private

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/collectory#217]
The links to them from bie and bie-test maps all go 'This resource is private'.

eg:

1. Go to species page  https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/2a4e373b-913a-4e2a-a53f-74828f6dae7e#overview

2. Under 'Compiled distribution maps' image, click the link for [BirdLife International species range maps](https://collections.ala.org.au/public/show/dr804)

3. Link directs to https://collections.ala.org.au/public/show/dr804, displays message "This resource is private"

**Comment by adam-collins** [comment]
These are now public. Not all were private. Data resources for expert distributions are `dr804` `dr803` `dr2099`
