### ISSUE TITLE
Fail to creating a collection when a user attempts to create a species list via Spatial Hub / List after the recent Auth plugin update

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/collectory#223]
Here is the process in Species list:

A user send a new specieslist  + user's token to the species list.
1, The species list verifies the token, and starts processing.
2, The species list send a request + its **own webservice token** to collections-test for creating a collection  
3, the collection-test responds 500 error

Checked the log in collection-test, the error:
` MissingMethodException occurred when processing request: [POST] /ws/dataResource
No signature of method: au.org.ala.collectory.ProviderGroupService._getEager() is applicable for argument types: (Node) values: [firstName=]`

I assume the last update on auth plugin tries to use the Token to retrieve a signed user details via the token. Since the token is a webservice token, it fails to retrieve user info

**Comment by adam-collins** [comment]
test environment bug fixed https://github.com/AtlasOfLivingAustralia/collectory/commit/d6f102d76bbb12e7268fd5e17c7843f684f5dc51
