### ISSUE TITLE
Logout button never changes to a Login one - on Collectory

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/collectory#224]
I can’t seem to log out of Collectory test. The Logout button never changes to a Login one, no matter how often I click it.

- Raised by @peggynewman 
- https://atlaslivingaustralia.slack.com/archives/C03EJ7ARZQW/p1702013081280859
-

**Comment by adam-collins** [comment]
Test config was out of date. Updated now. Is it working now?

**Comment by kylie-m** [comment]
Appears to work well for me now – @peggynewman is it working for you too now?

**Comment by peggynewman** [comment]
All good now, thanks!
