### ISSUE TITLE
Usage of apikeys in APIs

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/collectory#229]
[This API](https://docs.ala.org.au/openapi/index.html?urls.primaryName=metadata#/collection%2C%20institution%2C%20dataProvider%2C%20dataResource%2C%20tempDataResource%2C%20dataHub/getEntity) accepts apikey in header to give more information on dataResource connection details.
But you can try [the same API](https://collections.ala.org.au/ws/dataResource/dr10043) with apikey as a query param which gives you same information.
so i believe we might need to address this issue (using apikey as a query param and how we can use JWT instead of apikeys) if we want to completely decommission the apikeys.

**Comment by adam-collins** [comment]
JWT works for me
