### ISSUE TITLE
Collections-test Lists: Link on View public page pointing to Production

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/collectory#242]
In collections-test for a species list DR on the **Public View Page** the link  **View this species list in species list tool** is pointing to Production lists.

For example:

**dr22810**:  

- **Collectory:** https://collections-test.ala.org.au/dataResource/show/dr22810
- **Public Page:**  https://collections-test.ala.org.au/public/show/dr22810
- **View this species list in species list tool:** https://lists.ala.org.au/speciesListItem/list/dr22810

This has made testing changes to public/private status difficult.

**Comment by nickdos** [comment]
Config is using prod versions:

![image](https://github.com/user-attachments/assets/e1dffde0-960a-4e18-986c-64c0ca8e83f9)

**Comment by rosemaryjoconnor** [comment]
Which config is that Nick? Is it something that we can update?

**Comment by nickdos** [comment]
Fixed on test and in ansible-inventory files (see commits above).

**Comment by nickdos** [comment]
@rosemaryjoconnor please confirm this is now working as expected.

**Comment by rosemaryjoconnor** [comment]
Fixed Nick thanks so much!
