### ISSUE TITLE
Can't access metadata page for APPD collectory entry

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/collectory#42]
I need to access the metadata page for the Australian Plant Pest Database(http://collections.ala.org.au/public/showDataResource/dr1124), but when I try to get there I get the following Grails error:

![capture](https://cloud.githubusercontent.com/assets/8856025/6011872/bb15069e-ab94-11e4-9346-59d6a84ebde3.JPG)

Dave believes the error has been fixed in the new Collectory code but I can't test that as collections-test is down.  If it has been fixed, when will the new Collectory code be applied to the production server?

Thanks,

Michael.

**Comment by nickdos** [comment]
Alan can you check this in the new plugin version and fix if necessary?

**Comment by nickdos** [comment]
Looks like the prod page is working: http://collections.ala.org.au/public/showDataResource/dr1124 no longer returns an error for me.

**Comment by m-hope** [comment]
Sorry, I’m still getting the same error... in both IE and Chrome...

**Comment by nickdos** [comment]
URL for meta data page: 

http://collections.ala.org.au/dataResource/show/dr1124

Works in test but not prod...

http://collections-test.ala.org.au/ala-collectory/dataResource/show/dr1124
