### ISSUE TITLE
Grails 4 Upgrade

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/collectory#46]
Work underway on `develop` branch, a build is pushed to nexus.

Todo:
- [x] Enable CAS
- [x] File uploads in data resource pages
- [x] Fix logger stats on public pages
- [x] Check GBIF integration (data publishing and repatriation)
- [x] Charts on data resource, provider, collection and institution pages

**Comment by nickdos** [comment]
Might be safer to move to a branch, in case we need to deploy more changes to current 2.x version while dev still happening?

**Comment by djtfmartin** [comment]
As discussed this is a separate repo to collectory-plugin (currently used in prod)

**Comment by qifeng-bai** [comment]
1, Add an exisiting account to contact  throws an error: Error 500: Could not resolve view with name 'addContact' in servlet with name 'grailsDispatcherServlet'
https://github.com/AtlasOfLivingAustralia/collectory/issues/46

2,  Cannot edit range: Error 500: no transaction is in progress
Servlet: grailsDispatcherServlet
URI: /collection/range
https://collections-test.ala.org.au/collection/edit/co43?page=range

3, after successfully editing description,  browser shows JS issue:  ReferenceError: COLLECTORY_CONF is not defined

**Comment by djtfmartin** [comment]
Thanks @patkyn @qifeng-bai 
I've fixed the WS errors noticed with dp5183.

**Comment by djtfmartin** [comment]
Done and deployed with 3.0.1
