### ISSUE TITLE
admin page permissions issue

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/collectory#53]
Both https://collections.ala.org.au/admin and https://collections.ala.org.au/alaAdmin are not allowing access to users with ROLE_ADMIN. 

`/admin` is showing `You do not have access to admin tools. ROLE_ADMIN is required.` 
`/alaAdmin` is showing `Error 403`

Other pages that require ROLE_ADMIN are working fine, such as editting DR and CO pages, so could be the admin pages are not being routed via the correct AUTH filters.

EDIT: this is the setting on the server:
```properties
security.cas.uriFilterPattern=/admin.*,/collection.*,/institution.*,/contact.*,/reports.*,/providerCode.*,/providerMap.*,/dataProvider.*,/dataResource.*,/dataHub.*,/manage/.*,/alaAdmin.*
```

https://collections.ala.org.au/alaAdmin/buildInfo works so maybe the `.*` is not working as it should.

**Comment by nickdos** [comment]
Also noticed that if I create a new data resource, I don't see the button to delete the resource (should be at bottom - can see it on local dev machine but not test site, which indicates the AUTH config may be wrong on test).

**Comment by nickdos** [comment]
Looks like external config file is either not being loaded or being overridden by app-specific config file. As I see auth-test as server despite setting auth-prod in my config file.

**Comment by Rita-C** [comment]
https://collections-test.ala.org.au/admin and https://collections-test.ala.org.au/alaAdmin worked as expected.

**Comment by Rita-C** [comment]
"Delete" button shown and new dr deleted once clicked.
