### ISSUE TITLE
Error when trying to create a new data resource

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/collectory#55]
On https://collections.ala.org.au/dataResource/create

```
Error 500: Hibernate operation: could not execute statement; SQL [n/a]; Column 'attributions' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'attributions' cannot be null
Servlet: grailsDispatcherServlet
URI: /dataResource/create
Exception Message: Hibernate operation: could not execute statement; SQL [n/a]; Column 'attributions' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'attributions' cannot be null
Caused by: Hibernate operation: could not execute statement; SQL [n/a]; Column 'attributions' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'attributions' cannot be null
Class: AbstractHibernateGormInstanceApi
At Line: [248]
```

**Comment by nickdos** [comment]
code checked ✅

**Comment by nickdos** [comment]
Still seems to be broken on test site. On https://collections-test.ala.org.au/dataResource/list click the button "+ Add a new data resource". Page redirects back to same URL you started on but warning alert shows `Data resource not found with id in714`.

**Comment by nickdos** [comment]
Checking code, the `dataResource` domain class has contraints:

```groovy
    latitude(nullable:true)
    longitude(nullable:true)
```

But re-running app still shows same error. Looking at my DB, I can see the `data_resource` table lists these columns as NOT allowed to by nullable. I'm thinking a DB migration step might be required in the bootstrap.groovy class, possibly?
