### ISSUE TITLE
Can't view (or edit) a `dataHub` entity

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/collectory#60]
View a list of data hubs via https://collections-test.ala.org.au/dataHub/list

Click on one of the results, e.g. Australasian Virtual Herbarium - https://collections-test.ala.org.au/dataHub/show/dh9

Returns an error: 

```
Problem with your request
Error 500
URI: /dataHub/show/dh9
```

**Comment by nickdos** [comment]
Fixed error but page now shows `missing` when listing member collections or data resources. Clicking on any of these resolves the correct resource so bug is in lookup for the name.

![image](https://user-images.githubusercontent.com/532845/146718358-de3286d3-8eab-45e7-93a7-2f0ea0aaada5.png)

**Comment by Rita-C** [comment]
Code reviewed and tested on collections-test
