### ISSUE TITLE
Current i18n issues

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/collectory#92]
- [x] ![image](https://user-images.githubusercontent.com/180085/159706368-20371319-d331-4239-a83e-68b23de7c56a.png)

Mixed English/OtherLanguages in:

- [x] ![image](https://user-images.githubusercontent.com/180085/159707231-4a5f2bbd-3ee9-4acb-8f2c-63c3df7532ba.png)
- [x] ![image](https://user-images.githubusercontent.com/180085/159707745-cea1fae1-a9b1-448d-abad-1a882b857fa2.png)
- [x] ![image](https://user-images.githubusercontent.com/180085/159708030-593c9363-97ab-431b-81cf-77cf473d6cae.png)
- [x] Institutions: 
![image](https://user-images.githubusercontent.com/180085/159708636-639c59e3-c48e-4644-89f3-2200c60c33b4.png)
- [x] ![image](https://user-images.githubusercontent.com/180085/159709836-ba16aced-eca8-44c2-b6ce-40330605a764.png)
- [x]  ![image](https://user-images.githubusercontent.com/180085/159710270-ccc9ca09-7656-4aa3-b3e8-4d227af60777.png)
- [x] ![image](https://user-images.githubusercontent.com/180085/159710519-9da8d8d8-69e4-4dd1-8ca8-e5636396f06d.png)
- [x] ![image](https://user-images.githubusercontent.com/180085/159747335-79018fab-4d99-4de9-8c97-8c63c06c7b41.png)
- [x] ![image](https://user-images.githubusercontent.com/180085/159753638-628aa5ef-3bd4-481f-a3cf-23b85ef79501.png)
- [x] ![image](https://user-images.githubusercontent.com/180085/159769586-bd49778f-04fa-4ce7-8b33-e7c47a044c2e.png)
- [x] ![image](https://user-images.githubusercontent.com/180085/159770423-27fd6338-ad97-4852-89fc-0a32fb98f384.png)
- [x] ![image](https://user-images.githubusercontent.com/180085/159804633-14b10a87-8ef1-4858-a79a-98475760522e.png)
- [X] Fragmented sentences does not join correctly in other languages different than English:
![image](https://user-images.githubusercontent.com/180085/159868559-a5f21ba2-32aa-416a-bf04-06a1f6e8f944.png) 
- [X] ![image](https://user-images.githubusercontent.com/180085/159900821-d601cc78-b2cf-4a11-9d42-24caf434c0a8.png)
- [X] ![image](https://user-images.githubusercontent.com/180085/160023339-153ad655-d738-422a-a7a4-6a7f24f991ff.png)
- [X] ![image](https://user-images.githubusercontent.com/180085/160024067-de2b7a3f-a07d-48fd-9485-1133f544e8e2.png)
- [X] ![image](https://user-images.githubusercontent.com/180085/160109527-ae1fa8d6-9aab-4d93-8ca3-cd8329c6427b.png)
- [x] ![image](https://user-images.githubusercontent.com/180085/160121387-3ec7a5ce-9c6c-4382-b5ff-22d70c9e1438.png)
- [x] ![image](https://user-images.githubusercontent.com/180085/161041735-932edba6-1a32-47e7-8daa-d461a54e7585.png)

**Comment by vjrj** [comment]
One of the pending issues in the use of "Atlas", for instance:
![image](https://user-images.githubusercontent.com/180085/159975860-85ead62b-67c2-4ba9-a408-a65c5d22b8f5.png)
we have two options:
1. To define a new variable like `skin.orgAtlasBriefName='Atlas'` or `skin.orgAtlasBriefName='Portal'`
2. Use `ALA` from `skin.orgNameShort`, so the sentence will be "Contribution to ALA" instead (simpler).

This is a typical i18n issue that is present in other modules, so, maybe we should use 1) now and in other modules.

**Comment by nickdos** [comment]
`skin.orgNameShort` is consistent with biocache and bie code, so I think I'd prefer that, just so its consistent.
